print('What is the biggest lie in the entire universe?')
input()
print('I have read and agree to the Terms & Conditions.')
print()
print('How does a computer get drunk?')
input()
print('It takes screenshots.')
print()
print('Why did the computer show up at work late?')
input()
print("It had a hard drive.")
input()
print('What do you call an iPhone that isn’t kidding around?')
input()
print('Dead Siri-ous')
print()
print('Why was the cell phone wearing glasses?')
input()
print(' It lost its contacts.')
print()
print('Thank You that\'s all')
input()
print('yeah yeah yeah we are done')
